version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - PORT=3001
      # Pass through Storyblok env vars
      - VITE_STORYBLOK_TOKEN=${VITE_STORYBLOK_TOKEN}
      - VITE_STORYBLOK_VERSION=${VITE_STORYBLOK_VERSION:-published}
      - VITE_STORYBLOK_SPACE_ID=${VITE_STORYBLOK_SPACE_ID}
    volumes:
      # Persist SQLite database
      - sqlite_data:/app/data
      # Persist crawled data cache
      - crawler_cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3001/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local
  crawler_cache:
    driver: local
