version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - VITE_STORYBLOK_TOKEN=${VITE_STORYBLOK_TOKEN}
        - VITE_STORYBLOK_VERSION=${VITE_STORYBLOK_VERSION:-published}
        - VITE_STORYBLOK_SPACE_ID=${VITE_STORYBLOK_SPACE_ID}
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - PORT=3001
      # Runtime environment variables (not needed for built app)
      - VITE_STORYBLOK_TOKEN=${VITE_STORYBLOK_TOKEN}
      - VITE_STORYBLOK_VERSION=${VITE_STORYBLOK_VERSION:-published}
      - VITE_STORYBLOK_SPACE_ID=${VITE_STORYBLOK_SPACE_ID}
    volumes:
      - sqlite_data:/app/data
      - crawler_cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "fetch('http://localhost:3001/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local
  crawler_cache:
    driver: local
